# Site settings
title: Peter Delmeby
email: peter.delmeby@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A site about Peter Delmeby and related topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://delmeby.com"
twitter_username: Delodax
github_username:  Delodax

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
